#!/bin/bash
# NAME: JT_DWM
# DESC: An installation and deployment script for JaxTech's DWM Desktop.
# Adapted from Derek Taylor's (DistroTube) DTOS script...
# Top logo inspiration came from Chris Titus's ArchTitus script...


################################################################################
#################################### To Do #####################################
################################################################################



INSTALL_PATH=$(pwd)
LOG=$INSTALL_PATH/dwm_setup.log
rm $LOG > /dev/null 2>&1

clear

echo -ne "
   ████████╗  █████╗  ██╗   ██╗  ████████╗ ███████╗  ██████╗ ██╗  ██╗
   ╚══██╔══╝ ██╔══██╗  ██╗ ██╔╝  ╚══██╔══╝ ██╔════╝ ██╔════╝ ██║  ██║
      ██║    ███████║   ████╔╝      ██║    ███████╗ ██║      ███████║
   ██ ██║    ██╔══██║  ██╔╝██╗      ██║    ██╔════╝ ██║      ██╔══██║
   ╚███╔╝    ██║  ██║ ██╔╝  ██╗     ██║    ███████╗ ╚██████╗ ██║  ██║
    ╚══╝     ╚═╝  ╚═╝ ╚═╝   ╚═╝     ╚═╝    ╚══════╝  ╚═════╝ ╚═╝  ╚═╝
"
echo ""
echo " Jax|Tech Setup Script will launch in 5 seconds..."

sleep 5

clear

##################################################################################################
#################################### INSTALL BASE APPS ###########################################
##################################################################################################

sudo pacman -Syu git vim gcc make pkgconf xorg xorg-xinit feh ranger lightdm lightdm-gtk-greeter openssh -y 2>&1
sleep 5

clear

git clone https://git.suckless.org/dwm ~/dwm
sleep 5

git clone https://git.suckless.org/dmenu ~/dmenu
sleep 5

git clone https://git.suckless.org/st ~/st
sleep 5

git clone https://github.com/jaxtechnologies/wallpapers ~/wallpapers
sleep 5

clear

cd ~/dwm
sudo make clean install
sleep 5

cd ~/dmenu
sudo make clean install
sleep 5

cd ~/st
sudo make clean install
sleep 5

clear

feh –bg-fill ~/wallpapers/04_odin_dark.jpg

[ ! -d /usr/share/xsessions ] && sudo mkdir -p /usr/share/xsessions 2>&1 | tee -a $LOG
sudo cp $INSTALL_PATH/dwm.desktop /usr/share/xsessions/ 2>&1 | tee -a $LOG
cp $INSTALL_PATH/.xinitrc ~/.xinitrc 2>&1 | tee -a $LOG

systemctl enable lightdm
systemctl status lightdm

sleep 10

#########################################################################################
#################################### SETUP COMPLETE #####################################
#########################################################################################
clear
echo ""
read -p "Setup is Complete - Reboot the Machine NOW (y/n)? "
if [ "$REPLY" = "y" ]; then

  echo "" 2>&1 | tee -a $LOG
  echo Rebooting Now... 2>&1 | tee -a $LOG
  sudo reboot 2>&1 | tee -a $LOG
  sleep 2
  
else
	cancel
fi

exit
