#!/bin/bash
# NAME: JT_DWM
# DESC: An installation and deployment script for JaxTech's DWM Desktop.
# Adapted from Derek Taylor's (DistroTube) DTOS script...
# Top logo inspiration came from Chris Titus's ArchTitus script...


################################################################################
#################################### To Do #####################################
################################################################################



INSTALL_PATH=$(pwd)
LOG=$INSTALL_PATH/dwm_setup.log
rm $LOG > /dev/null 2>&1

clear

echo -ne "
   ████████╗  █████╗  ██╗   ██╗  ████████╗ ███████╗  ██████╗ ██╗  ██╗
   ╚══██╔══╝ ██╔══██╗  ██╗ ██╔╝  ╚══██╔══╝ ██╔════╝ ██╔════╝ ██║  ██║
      ██║    ███████║   ████╔╝      ██║    ███████╗ ██║      ███████║
   ██ ██║    ██╔══██║  ██╔╝██╗      ██║    ██╔════╝ ██║      ██╔══██║
   ╚███╔╝    ██║  ██║ ██╔╝  ██╗     ██║    ███████╗ ╚██████╗ ██║  ██║
    ╚══╝     ╚═╝  ╚═╝ ╚═╝   ╚═╝     ╚═╝    ╚══════╝  ╚═════╝ ╚═╝  ╚═╝
"
echo ""
echo " Jax|Tech Setup Script will launch in 5 seconds..."

sleep 5

clear

##################################################################################################
#################################### INSTALL BASE APPS ###########################################
##################################################################################################

	sudo pacman -Syu git vim gcc make pkgconf xorg xorg-xinit feh ranger lightdm lightdm-gtk-greeter openssh -y 2>&1
	
	git clone https://git.suckless.org/dwm
	git clone https://git.suckless.org/demu
	git clone https://git.suckless.org/st
	git clone https://github.com/jaxtechnologies/wallpapers
	
	cd dwm
	sudo make clean install
	cd ..
	
	cd dmenu
	sudo make clean install
	cd ..
	
	cd st
	sudo make clean install
	cd ..

	feh –bg-fill ~/wallpapers/04_odin_dark.jpg

    [ ! -d /usr/share/xsessions ] && sudo mkdir -p /usr/share/xsessions 2>&1 | tee -a $LOG
    sudo cp $INSTALL_PATH/configs/dwm.desktop /usr/share/xsessions/ 2>&1 | tee -a $LOG
    cp $INSTALL_PATH/configs/.xinitrc ~/.xinitrc 2>&1 | tee -a $LOG
    clear

	systemctl enable lightdm
	systemctl status lightdm

#########################################################################################
#################################### SETUP COMPLETE #####################################
#########################################################################################
clear
echo ""
read -p "Setup is Complete - Reboot the Machine NOW (y/n)? "
if [ "$REPLY" = "y" ]; then

  echo "" 2>&1 | tee -a $LOG
  echo Rebooting Now... 2>&1 | tee -a $LOG
  sudo reboot 2>&1 | tee -a $LOG
  sleep 2
  
else
	cancel
fi

exit
