#!/bin/sh
# This script is used to manage key events while viewing images with sxiv

while read file
do
  case "$1" in
  "C-d")
      mv "$file" ~/.trash ;;
  "C-r")
      convert -rotate 90 "$file" "$file" ;;
  "C-c")
      echo -n "$file" | xclip -selection clipboard ;;
  "C-w")
      wal -i "$file" ;;
  esac
done
